# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

models:
  - name: Qwen 2.5 Coder 32B
    provider: openai
    model: Qwen2.5-Coder-32B-Instruct-Q6_K.gguf
    api_base: http://127.0.0.1:8080/v1
    roles:
      - chat
      - edit
      - apply

tab_autocomplete_model:
  name: Qwen 2.5 Coder Auto
  provider: openai
  model: Qwen2.5-Coder-32B-Instruct-Q6_K.gguf
  api_base: http://127.0.0.1:8080/v1

allow_anonymous_telemetry: false