name: Generate Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Doxygen and Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Run Doxygen
      run: doxygen Doxyfile

    - name: Commit and Push Documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f docs/
        git commit -m "Update documentation [skip ci]" || echo "No changes to commit"
        git push
